### ISSUE TITLE
COPY FROM causes the crash error

### ISSUE THREAD

**Issue by redsiren204** [pgspider/griddb_fdw#10]
COPY FROM does not work now. And it causes the crash error:
```SQL
create foreign table rem2 (f1 int, f2 text) server griddb_svr options(table_name 'loc2');
copy rem2 from stdin;
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
select * from rem2;
no connection to the server
connection to server was lost
```
Could you please confirm this function is supported or not?
And I think the crash error should not occur.

**Comment by t-kataym** [comment]
Thank you for the report.
It will be fixed soon.

**Comment by t-kataym** [comment]
I fixed the issue. Could you confirm it?

**Comment by redsiren204** [comment]
Yes. I re-tested with the latest commit and this issue is fixed.
