### ISSUE TITLE
Request to improve aggregation push-down

### ISSUE THREAD

**Issue by kanegoon** [pgspider/griddb_fdw#2]
GridDB has same SQL aggregation functions to PostgreSQL. Such as SUM(), COUNT() and so on. But I can not push down SQL aggregation functions.
Could you please improve aggregation push-down?

**Comment by nxhai98** [comment]
Hello @kanegoon,

Thank you for your suggestion.
 
From version 2.0.0, griddb_fdw already support aggregate function push down:
> Support aggregation push down:
> 
> Common functions of Postgres and Griddb are pushed down: min, max, count(*), sum, avg, variance, stddev.
> Unique function of Griddb are pushed down: time_avg

For more detail please refer: https://github.com/pgspider/griddb_fdw/releases/tag/v2.0.0

Could you confirm it is as your expectation?

**Comment by hrkuma** [comment]
Thank you for confirmation.
I confirmed the current status.
So I'd like to close this issue.
