### ISSUE TITLE
Error griddb_fdw test using "make check" on postgresql 11.0

### ISSUE THREAD

**Issue by redsiren204** [pgspider/griddb_fdw#3]
It cannot complete regression test using "make check" command. The issue occurs below:
```
SELECT * FROM department d, employee e WHERE d.department_id = e.emp_dept_id LIMIT 10;                                                                   
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
connection to server was lost
```
The sql querry causes the error is `SELECT * FROM department d, employee e WHERE d.department_id = e.emp_dept_id LIMIT 10;`
Following the log of the PostgreSQL server, I found out the error in griddb_fdw.c, line 857:
```
TRAP: FailedAssertion("!(fsstate->cursor == fsstate->num_tuples)", File: "griddb_fdw.c", Line: 857)
2018-12-26 15:45:56.052 +07 [5763] LOG:  server process (PID 5781) was terminated by signal 6: Aborted
2018-12-26 15:45:56.052 +07 [5763] DETAIL:  Failed process was running: SELECT * FROM department d, employee e WHERE d.department_id = e.emp_dept_id LIMIT 10;
```
The log of PostgreSQL server is attached: [postmaster.log](https://github.com/pgspider/griddb_fdw/files/2712156/postmaster.log)

**Comment by t-kataym** [comment]
Thank you for the report.
The assertion is not correct. I will fix it.

**Comment by t-kataym** [comment]
I fixed.
