### ISSUE TITLE
Can not update a null column to not-null value

### ISSUE THREAD

**Issue by redsiren204** [pgspider/griddb_fdw#8]
I would like to report an issue. Null value is supported now, but we can not update a null column to not-null value.
Could you please confirm and fix this issue?

**Comment by t-kataym** [comment]
I think it is the issue of GridDB C client.
It has been updated recently.
https://github.com/griddb/c_client
Could you confirm again?

**Comment by redsiren204** [comment]
Your explanation is correct. This issue is belong to C client.
I installed the latest version of C client and this issued is fixed.
