### ISSUE TITLE
The partitioning feature cause the crash error

### ISSUE THREAD

**Issue by redsiren204** [pgspider/griddb_fdw#9]
Regarding to table partitioning feature, I got a crash error by the following scenario:
```SQL
create table itrtest (a int, b text) partition by list (a);
create foreign table remp1 (a int, b text) server griddb_svr options (table_name 'locp1');
alter table itrtest attach partition remp1 for values in (1);
insert into itrtest values (1, 'foo');
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
connection to server was lost
```
Does GridDB FDW support the table partitioning feature?
Anyway, the server crashing should not occur. Could you please fix this issue.

**Comment by t-kataym** [comment]
Thank you for the report.
The issue is fixed by #10's fix partially(INSERT&SELECT).
But need additional modification for UPDATE/DELETE query.

**Comment by t-kataym** [comment]
I fixed. Could you confirm it?

**Comment by redsiren204** [comment]
I confirmed that this issue is fixed.
